# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/DSD-II/Exercise2/Project2/Project2.cache/wt [current_project]
set_property parent.project_path D:/DSD-II/Exercise2/Project2/Project2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/DSD-II/Exercise2/Project2/Project2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/DSD-II/Exercise2/Project2/Project2.srcs/sources_1/new/andN.vhd
  D:/DSD-II/Exercise2/Project2/Project2.srcs/sources_1/new/decoder.vhd
  D:/DSD-II/Exercise2/Project2/Project2.srcs/sources_1/new/mux.vhd
  D:/DSD-II/Exercise2/Project2/Project2.srcs/sources_1/new/reg_module.vhd
  D:/DSD-II/Exercise2/Project2/Project2.srcs/sources_1/new/reg_file.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top reg_file -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef reg_file.dcp

catch { report_utilization -file reg_file_utilization_synth.rpt -pb reg_file_utilization_synth.pb }
